version: "3"

services:

  client:
    build: ./client
    dockerfile: ./client/Dockerfile.prod
    network_mode: host
    depends_on:
      - server
    ports:
      - 80:80

  server:
    build: ./server
    dockerfile: ./server/Dockerfile.prod
    ports:
      - 8080:8080

  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
 
volumes:
  db: