version: "3.7"

services:

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    tty: true
    environment: 
      - TERM=xterm-256color`
    env_file:
      .env
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    volumes:
      - ./server:/app
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    env_file:
      .env
    ports:
      - ${MONGO_PORTS}:${MONGO_PORTS}
    volumes:
      - mongo:/data/db

  redis:
    image: redis:6.0.1-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    depends_on:
      - mongo

volumes:
  redis:
  mongo:
