version: "3"

services:

  client:
    build: ./client
    dockerfile: ./client/Dockerfile.prod
    env_file:
      .env.prod
    depends_on:
      - server
    ports:
      - 80:80

  server:
    build: ./server
    dockerfile: ./server/Dockerfile.prod
    env_file:
      .env.prod
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    image: postgres:12.2-alpine
    env_file:
      .env.prod
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
 
  redis:
    image: redis:6.0.1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
