version: "3"

services:

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app

  server:
    build: ./server
    env_file:
      .env
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    image: postgres:12.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  redis:
    image: redis:6.0.1-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
