version: "3.7"

services:

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    tty: true
    environment: 
      - TERM=xterm-256color`
    env_file:
      .env
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    volumes:
      - ./server:/app
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

  mongo:
    image: mongo:4.4-rc
    restart: always
    env_file:
      .env
    ports:
      - ${MONGO_PORTS}:${MONGO_PORTS}
    volumes:
      - mongo:/data/db

  redis:
    image: redis:6.0.1-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    depends_on:
      - mongo

  # netdata:
  #   image: netdata/netdata
  #   container_name: netdata
  #   hostname: example.com # set to fqdn of host
  #   environment:
  #     - DO_NOT_TRACK=1
  #   ports:
  #     - 19999:19999
  #   restart: unless-stopped
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined
  #   volumes:
  #     - netdatalib:/var/lib/netdata
  #     - netdatacache:/var/cache/netdata
  #     - /etc/passwd:/host/etc/passwd:ro
  #     - /etc/group:/host/etc/group:ro
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /etc/os-release:/host/etc/os-release:ro

volumes:
  redis:
  mongo:
  # netdatalib:
  # netdatacache:
