version: "3.7"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    env_file:
      .env.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/live/justonecanvas.live/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/justonecanvas.live/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - server
    links:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    tty: true
    env_file:
      .env.prod
    environment: 
      - TERM=xterm-256color`
    ports:
      - 8080
    volumes:
      - ./server:/app
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

  mongo:
    image: mongo:4.4-rc
    restart: always
    env_file:
      .env.prod
    ports:
      - ${MONGO_PORTS}:${MONGO_PORTS}
    volumes:
      - mongo:/data/db
 
  redis:
    image: redis:6.0.1-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      .env.prod
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    depends_on:
      - mongo

volumes:
  redis:
  mongo:
